#ifndef QPK11SETPASSWORD_GLOBAL_H
#define QPK11SETPASSWORD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPK11SETPASSWORD_LIBRARY)
#  define QPK11SETPASSWORD_EXPORT Q_DECL_EXPORT
#else
#  define QPK11SETPASSWORD_EXPORT Q_DECL_IMPORT
#endif

#endif // QPK11SETPASSWORD_GLOBAL_H
